Update small CTA to adjust content alignment
AlaskaAirlines/auro-hyperlink pull request #192
Opened 2024-01-06 23:48 UTC by blackfalcon

# Alaska Airlines Pull Request

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

**Fixes:** #191 

## Summary:

_Please summarize the scope of the changes you have submitted, what the intent of the work is and anything that describes the before/after state of the project._

There was mainly an issue with the placement of an icon within the small CTA use case. The update allows for easier management of the additional content.

A couple of stylelint rules were slightly adjusted to allow for new code without having to also do a code refactor to meet linting needs.

Changes to be committed:
modified:   .stylelintrc
modified:   src/style.scss

### Before

<img width="1098" alt="Screen Shot 2024-01-06 at 2 23 34 PM" src="https://github.com/AlaskaAirlines/auro-hyperlink/assets/181089/11742ab7-d648-4386-bdf7-4654ced4d489">

### After

<img width="812" alt="Screen Shot 2024-01-06 at 3 37 36 PM" src="https://github.com/AlaskaAirlines/auro-hyperlink/assets/181089/280f5059-b5a9-43d7-a7b2-6b2a54e290ab">

## Type of change:

Please delete options that are not relevant.

- [ ] New capability
- [x] Revision of an existing capability
- [ ] Infrastructure change (automation, etc.)
- [ ] Other (please elaborate)

## Checklist:

- [x] My update follows the CONTRIBUTING guidelines of this project
- [x] I have performed a self-review of my own update

**By submitting this Pull Request, I confirm that my contribution is made under the terms of the Apache 2.0 license.**

_Pull Requests will be evaluated by their quality of update and whether it is consistent with the goals and values of this project. Any submission is to be considered a conversation between the submitter and the maintainers of this project and may require changes to your submission._

**Thank you for your submission!**<br>
-- Auro Design System Team

2024-01-08 18:20 UTC, leeejune submitted a review, later dismissed
YES THANK YOU! THIS IS GREAT!

2024-01-08 22:25 UTC, jason-capsule42 requested changes

2024-01-08 22:25 UTC, jason-capsule42 commented on src/style.scss
> +  top: 2px;
```suggestion
  top: var(--ds-size-25, $ds-size-25);
```

2024-01-09 00:51 UTC, jason-capsule42 approved these changes

2024-01-17 19:48 UTC, merged

2024-01-17 19:50 UTC, blackfalcon commented
:tada: This PR is included in version 3.4.2 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/@aurodesignsystem/auro-hyperlink/v/3.4.2)
- [GitHub release](https://github.com/AlaskaAirlines/auro-hyperlink/releases/tag/v3.4.2)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: