[Feature]: New 'tertiary' variant
AlaskaAirlines/auro-hyperlink pull request #205
Opened 2024-04-25 07:59 UTC by fajar-apri-alaska

# Alaska Airlines Pull Request

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

**Resolves:** #204 (issue, if applicable)

## Summary:

This PR is to provides 'tertiary' option for CTA-hyperlink per ticket #204.

- add the new feature example to apiExamples
- also update generateDocs script to fix the issue in macOS based machines

## Type of change:

Please delete options that are not relevant.

- [x] New capability
- [ ] Revision of an existing capability
- [ ] Infrastructure change (automation, etc.)
- [x] Generator script update

## Checklist:

- [x] My update follows the CONTRIBUTING guidelines of this project
- [x] I have performed a self-review of my own update

**By submitting this Pull Request, I confirm that my contribution is made under the terms of the Apache 2.0 license.**

_Pull Requests will be evaluated by their quality of update and whether it is consistent with the goals and values of this project. Any submission is to be considered a conversation between the submitter and the maintainers of this project and may require changes to your submission._

**Thank you for your submission!**<br>
-- Auro Design System Team

2024-04-25 08:10 UTC, fajar-apri-alaska commented
Hi team,
News are, the key token values are a bit different with the one from blueprints (still using --auro instead of --ds).
I tried to map out per the latest ones. But I'm still not sure since some value are a bit off by it looks after it is rendered on the browser. So if anything is a miss from my side, please tell me so.
Thanks.

Figma/Blueprint links:
https://github.com/AlaskaAirlines/auro-hyperlink/issues/204#issuecomment-2061749224

2024-04-25 18:34 UTC, blackfalcon commented
> Hi team, News are, the key token values are a bit different with the one from blueprints (still using --auro instead of --ds). I tried to map out per the latest ones. But I'm still not sure since some value are a bit off by it looks after it is rendered on the browser. So if anything is a miss from my side, please tell me so. Thanks.
> 
> Figma/Blueprint links: [#204 (comment)](https://github.com/AlaskaAirlines/auro-hyperlink/issues/204#issuecomment-2061749224)

@leeejune please take note that the Figma blueprint is still referencing `--auro-` versus `--ds`.

2024-04-25 19:46 UTC, blackfalcon requested changes

2024-04-26 03:33 UTC, fajar-apri-alaska commented on scripts/generateDocs.mjs
> +const __dirname = fileURLToPath(new URL('.', import.meta.url));
Hi @blackfalcon,
this is related to last concern in our discussion by chat.

So, when I used the old script: new URL('.', import.meta.url).pathname, it returns the encoded path 
 
`/Users/fajar_a/Git%20Project/AlaskaAirlines/auro-flight/scripts/`
 
that doesn't work on my machine, and will return like below example from my machine.
<img width="1440" alt="image" src="https://github.com/AlaskaAirlines/auro-hyperlink/assets/124668226/417bcf7b-579d-4269-93f0-e922bd89bf4f">
*screenshot taken from auro-flight
 
Meanwhile using fileURLToPath(new URL('.', import.meta.url)), would return
 
`/Users/fajar_a/Git Project/AlaskaAirlines/auro-flight/scripts/`
 
it now works, and render the documentation as expected.

--- 

Should I just do the script on my end only then? I can excludes the change to the script for this commit.

2024-05-07 18:57 UTC, blackfalcon approved these changes

2024-05-07 18:58 UTC, merged

2024-05-07 19:00 UTC, blackfalcon commented
:tada: This PR is included in version 3.6.0 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/@aurodesignsystem/auro-hyperlink/v/3.6.0)
- [GitHub release](https://github.com/AlaskaAirlines/auro-hyperlink/releases/tag/v3.6.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: